apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-auth
spec:
  selector:
    matchLabels:
      app: treetracker-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: treetracker-auth
    spec:
      hostAliases:
        - ip: "192.168.0.104"
          hostnames:
          - "treetracker.local"
      containers:
      - name: treetracker-auth
        image: dadiorchen/treetracher-auth:test1
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: treetracker-auth-service
  annotations:
spec:
  ports:
  - name: http
    port: 80
    targetPort: 3000
  selector:
    app: treetracker-auth

