apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: test-api
build:
  artifacts:
  - image: treetracker-test-api
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s.yaml
